language: cpp
compiler:
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get install cmake libphysfs-dev
  - git clone https://github.com/LaurentGomila/SFML.git sfml
  - mkdir build-sfml
  - cd build-sfml
  - cmake -G "Unix Makefiles" ../sfml
  - make
  - make install
before_script:
  - cd ..
  - mkdir build-hikari
  - cd build-hikari
script: cmake -G "Unix Makefiles" ../hikari
branches:
  only:
    - master
notifications:
  recipients:
    - hikari@zackthehuman.com
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.boxbox.org#hikari"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
  - linux
