language: cpp
compiler: clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get install cmake libudev-dev libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libsndfile1-dev libopenal-dev libphysfs-dev
  - cd ..
  - git clone https://github.com/LaurentGomila/SFML.git sfml
  - mkdir build-sfml
  - cd build-sfml
  - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=TRUE ../sfml
  - sudo make
  - sudo make install
before_script:
  - pwd
  - ls
  - cd ..
  - mkdir build-hikari
  - cd build-hikari
script: cmake -G "Unix Makefiles" ../hikari; sudo make
branches:
  only:
    - master
notifications:
  recipients:
    - hikari@zackthehuman.com
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.boxbox.org#hikari"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
  - linux
